#!/usr/bin/env python3
#-*-encoding:utf-8*-

import os
import sys
import random

from lib import *

# TODO    Pomodoro timer
# TODO    Add notes
# TODO    Todo list, separated by categories
#    For each element on todo list, allow to create sub-todos
#    Do this indefinitely
#    For each todo, allow to take notes, to create a pomodoro timer

# TODO    After actions on commands, have a menu display to see possible actions
#    Anything that forwards to other services

# TODO    Add docgen tool to this

class Assistant:
    def __init__(self):
        self.storage = datastore.Datastore("ass")

    def act(self, command, args, *a, **k):
        # TODO    Add option to bind to a pomodoro timer
        if command == "choose":
            fname = self.storage.data_path("priorize", args.name)
            return priorize.act(fname, *a, **k)

        elif command == "edit":
            self.storage.edit_data(args.category, args.name)
            return None

        elif command == "aicha":
            assistant = ai.AiAssistant(self.storage.cache_path("aicha"))
            return assistant.act(args)

        else:
            raise Exception(f"Command {command} defined but not implemented")

if __name__ == "__main__":
    cliargs = cli.get_args()
    assistant = Assistant()
    assistant.act(cli.get_command(cliargs.command), cliargs, verbose=cliargs.verbose)
