#!/usr/bin/env python3
#-*-encoding:utf-8*-

import os
import sys
import random

from lib import *

COMMANDS = {
    "priorize": {
        "aliases": ["p", "prio"],
        "short_help": "Pick things to do based on priorities set",
        "setup_parser": priorize.setup,
    },
    "edit": {
        "aliases": ["e"],
        "short_help": "Edit a data file contained in the assistant data dir",
        "setup_parser": setup_edit_parser,
    },
}

def get_command(raw):
    if raw in COMMANDS:
        return raw
    else:
        for cmd, data in COMMANDS.items():
            if raw in data["aliases"]:
                return cmd
        return None

class Assistant:
    def __init__(self, data_dir = None):
        if not data_dir:
            data_dir = os.path.join(
                os.path.dirname(os.path.realpath(sys.argv[0])),
                "data",
            )
        self.data_dir = data_dir

    def priorize(self, fname, *a, verbose = False, **k):
        if not os.path.isfile(fname):
            print("File does not exist")
            print(f"It should exist at {fname}")
            return

        pick = priorize.PrioPick(verbose)
        k = pick.import_file(fname)
        if verbose:
            print(f"Probabilities for {k} picks:")
            pick.print_probas(k)
        got = pick.pick(k)
        if any([got.count(val) != 1 for val in got]):
            raise Exception(f"Error on data: {got}")
        print("Choices:", ", ".join(got))

    def edit_file(self, fname, *a, **k):
        if not os.getenv("EDITOR"):
            raise Exception("EDITOR environment variable not set")
        os.system(f"$EDITOR {fname}")

    def get_arg(self, args, index):
        if index >= len(args):
            raise Exception("Expected name argument")
        return args[index]

    def get_fname_from_args(self, args, index, *subf):
        fname = self.get_arg(args, index)
        return os.path.join(self.data_dir, *subf, fname)

    def act(self, command, args, *a, **k):
        # TODO    Add option to bind to a pomodoro timer
        if command == "priorize":
            fname = os.path.join(self.data_dir, "priorize", args.name)
            return self.priorize(fname, *a, **k)

        elif command == "edit":
            fname = os.path.join(self.data_dir, args.category, args.name)
            return self.edit_file(fname, *a, **k)

if __name__ == "__main__":
    cliargs = get_args(COMMANDS)
    assistant = Assistant()
    assistant.act(get_command(cliargs.command), cliargs, verbose=cliargs.verbose)
